### ISSUE TITLE
Исправления com.c для Linux

### ISSUE THREAD

**Issue by iLya2IK** [Polarisru/updiprog#14]
Исли вам будет интересно, внес некоторые изменения в файл com.c для быстрой и надежной работы с последовательным портом под Linux (тестировал только под OpenSUSE и Ubuntu). Добавил также кое-что по-мелочи в ваш код, адаптировал код под сборку динамической библиотеки, добавил пример ее использования в GUI-приложении.

https://github.com/iLya2IK/updiprog

С уважением,

**Comment by Polarisru** [comment]
Доброго дня! Выглядит интересно. А под Win такое тоже можно собрать?

**Comment by iLya2IK** [comment]
Да. Там же есть сборка под Win64

**Comment by Polarisru** [comment]
А можно это синхронизировать с исходным проектом? Было бы интересно иметь возможность работать и из GUI

**Comment by iLya2IK** [comment]
Конечно можно) отправил запрос на слияние
